### PR TITLE
Navigation style-adjustments

### PR DESCRIPTION
**Pull request by rottabonus**
# Description

Style adjustments found in last sprint-planning session, fixes issues in following [Trello-card](https://trello.com/c/mIWzlnBv/758-small-style-fixes-for-navigation)

## Why was the change made?

- Make the designs more close to the designs, 
- Remove i18n-warnings from jest-tests
- Refactor code for better readability and follow project conventions

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Ran jest tests, and tsc

- [x] Unittest
- [ ] Cypress e2e -tests

# Caveats?

- Small refactoring, created two new components for logic abstraction.
- One new hook, useHover. I opted to use a hook for hovering because it was easiest and most readable way (I figured out fast enough ) to fix the fill-property for the icon-component on hover-effect. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kuosmark** [comment]
A few things I noticed:
- The Language and Info Dropdowns use the light blue color #CDE8F8 when hovering over them, whereas the Figma design has the on-hover color as #D3EFFF.

- The navigation bar breaks like this at two points between the mobile and desktop versions. It breaks when the screen width is between 600 and 650 or 730 and 810 pixels wide.
Screenshot 2023-01-11 at 9 45 42

- Really nitpicking: You almost don't see it, but it looks like the Ylitse logo (the YLITSE text) is not completely centered as it appears in the design.

**Comment by kuosmark** [comment]
Oh yeah, the navigation bar is so beautiful now when I adjust the screen size! 🥲

But I found one more thing to change for screen widths 650-830! For these widths, the Ylitse y-logo doesn't have any margin on its left. 👇 

Screenshot 2023-01-13 at 10 25 53

And to me it seems that the on-hover color is now #E4F3FB, not #D3EFFF 😄 Seems like the palette variable doesn't have the correct color yet.

**Comment by rottabonus** [comment]
> Oh yeah, the navigation bar is so beautiful now when I adjust the screen size! 🥲
> 
> But I found one more thing to change for screen widths 650-830! For these widths, the Ylitse y-logo doesn't have any margin on its left. 👇
> 
> Screenshot 2023-01-13 at 10 25 53
> 
> And to me it seems that the on-hover color is now #E4F3FB, not #D3EFFF 😄 Seems like the palette variable doesn't have the correct color yet.

It seems that we had a wrong color in the lightblue variable. It was not part of the Figma-palette. Changed it to #D3FFF and used it.

**Review by kuosmark — APPROVED** [review]
Nice work!! :)

**Pull request merged**
